# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:

name: playwright.yaml

permissions: read-all

jobs:
  playwright:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests/playwright

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: 🕸️ Install dependencies
        run: npm ci

      - name: 🕸️ Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: 🧪 Run Playwright tests
        run: npx playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: tests/playwright/playwright-report/
          retention-days: 30

